services:
  # ========================================
  # PostgreSQL
  # ========================================
  postgres:
    image: postgres:16
    container_name: dev-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - dev-network

  # ========================================
  # pgAdmin
  # ========================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - dev-network

  # ========================================
  # MongoDB
  # ========================================
  mongodb:
    image: mongo:7
    container_name: mongo_server
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge